# Used https://gist.github.com/dan-blanchard/7045057
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose shapely pandas matplotlib bokeh 
  - pip install coveralls descartes pyyaml 

script:
  - nosetests --with-coverage

after_success:
  - coveralls
