# Used https://gist.github.com/dan-blanchard/7045057
language: python
python:
  - "3.3"
  - "3.4"

before_install:
  - pip install conda
  - conda init

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose shapely pandas
  - pip install coveralls

script:
  - nosetests --with-coverage

after_success:
  - coveralls
